import { Component, Leaner, LeanerNode, LeanerElement } from './web';

declare global {
  namespace JSX {
    type ElementType = string | ( ( props: any, children: LeanerNode[] ) => LeanerNode );

    type Element = LeanerElement;

    interface IntrinsicElements {
      a: Leaner.HTMLAnchorProps;
      abbr: Leaner.HTMLProps;
      address: Leaner.HTMLProps;
      area: Leaner.HTMLAreaProps;
      article: Leaner.HTMLProps;
      aside: Leaner.HTMLProps;
      audio: Leaner.HTMLAudioProps;
      b: Leaner.HTMLProps;
      base: Leaner.HTMLBaseProps;
      bdi: Leaner.HTMLProps;
      bdo: Leaner.HTMLProps;
      blockquote: Leaner.HTMLQuoteProps;
      body: Leaner.HTMLProps<HTMLBodyElement>;
      br: Leaner.HTMLProps<HTMLBRElement>;
      button: Leaner.HTMLButtonProps;
      canvas: Leaner.HTMLCanvasProps;
      caption: Leaner.HTMLProps<HTMLTableCaptionElement>;
      cite: Leaner.HTMLProps;
      code: Leaner.HTMLProps;
      col: Leaner.HTMLTableColProps;
      colgroup: Leaner.HTMLTableColProps;
      data: Leaner.HTMLDataProps;
      datalist: Leaner.HTMLProps<HTMLDataListElement>;
      dd: Leaner.HTMLProps;
      del: Leaner.HTMLModProps;
      details: Leaner.HTMLDetailsProps;
      dfn: Leaner.HTMLProps;
      dialog: Leaner.HTMLDialogProps;
      div: Leaner.HTMLProps<HTMLDivElement>;
      dl: Leaner.HTMLProps<HTMLDListElement>;
      dt: Leaner.HTMLProps;
      em: Leaner.HTMLProps;
      embed: Leaner.HTMLEmbedProps;
      fieldset: Leaner.HTMLFieldSetProps;
      figcaption: Leaner.HTMLProps;
      figure: Leaner.HTMLProps;
      footer: Leaner.HTMLProps;
      form: Leaner.HTMLFormProps;
      h1: Leaner.HTMLProps<HTMLHeadingElement>;
      h2: Leaner.HTMLProps<HTMLHeadingElement>;
      h3: Leaner.HTMLProps<HTMLHeadingElement>;
      h4: Leaner.HTMLProps<HTMLHeadingElement>;
      h5: Leaner.HTMLProps<HTMLHeadingElement>;
      h6: Leaner.HTMLProps<HTMLHeadingElement>;
      head: Leaner.HTMLProps<HTMLHeadElement>;
      header: Leaner.HTMLProps;
      hgroup: Leaner.HTMLProps;
      hr: Leaner.HTMLProps<HTMLHRElement>;
      html: Leaner.HTMLProps<HTMLHtmlElement>;
      i: Leaner.HTMLProps;
      iframe: Leaner.HTMLIFrameProps;
      img: Leaner.HTMLImageProps;
      input: Leaner.HTMLInputProps;
      ins: Leaner.HTMLModProps;
      kbd: Leaner.HTMLProps;
      label: Leaner.HTMLLabelProps;
      legend: Leaner.HTMLProps<HTMLLegendElement>;
      li: Leaner.HTMLLIProps;
      link: Leaner.HTMLLinkProps;
      main: Leaner.HTMLProps;
      map: Leaner.HTMLMapProps;
      mark: Leaner.HTMLProps;
      menu: Leaner.HTMLProps<HTMLMenuElement>;
      meta: Leaner.HTMLMetaProps;
      meter: Leaner.HTMLMeterProps;
      nav: Leaner.HTMLProps;
      noscript: Leaner.HTMLProps;
      object: Leaner.HTMLObjectProps;
      ol: Leaner.HTMLLOListProps;
      optgroup: Leaner.HTMLOptGroupProps;
      option: Leaner.HTMLOptionProps;
      output: Leaner.HTMLOutputProps;
      p: Leaner.HTMLProps<HTMLParagraphElement>;
      picture: Leaner.HTMLProps<HTMLPictureElement>;
      pre: Leaner.HTMLProps<HTMLPreElement>;
      progress: Leaner.HTMLProgressProps;
      q: Leaner.HTMLQuoteProps;
      rp: Leaner.HTMLProps;
      rt: Leaner.HTMLProps;
      s: Leaner.HTMLProps;
      samp: Leaner.HTMLProps;
      script: Leaner.HTMLScriptProps;
      search: Leaner.HTMLProps;
      section: Leaner.HTMLProps;
      select: Leaner.HTMLSelectProps;
      slot: Leaner.HTMLSlotProps;
      small: Leaner.HTMLProps;
      source: Leaner.HTMLSourceProps;
      span: Leaner.HTMLProps<HTMLSpanElement>;
      strong: Leaner.HTMLProps;
      style: Leaner.HTMLStyleProps;
      sub: Leaner.HTMLProps;
      summary: Leaner.HTMLProps;
      sup: Leaner.HTMLProps;
      table: Leaner.HTMLProps<HTMLTableElement>;
      tbody: Leaner.HTMLProps<HTMLTableSectionElement>;
      td: Leaner.HTMLTableCellProps;
      template: Leaner.HTMLProps<HTMLTemplateElement>;
      textarea: Leaner.HTMLTextAreaProps;
      tfoot: Leaner.HTMLProps<HTMLTableSectionElement>;
      th: Leaner.HTMLTableCellHeaderProps;
      thead: Leaner.HTMLProps<HTMLTableSectionElement>;
      time: Leaner.HTMLTimeProps;
      title: Leaner.HTMLProps<HTMLTimeElement>;
      tr: Leaner.HTMLProps<HTMLTableRowElement>;
      track: Leaner.HTMLTrackProps;
      u: Leaner.HTMLProps;
      ul: Leaner.HTMLProps<HTMLUListElement>;
      var: Leaner.HTMLProps;
      video: Leaner.HTMLVideoProps;
      wbr: Leaner.HTMLProps;

      catch: {};
      dynamic: { is: () => string | Component, [ K: string ]: any };
      else: {};
      for: { items: () => readonly any[] };
      if: { match: () => boolean };
      repeat: { count: number | ( () => number ) };
      switch: {};
      try: {};
    }
  }
}
